unit fClientForm;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs, StdCtrls,
  uROClient, uROClientIntf, uRORemoteService, uROBinMessage, uROWinInetHTTPChannel;

type
  TClientForm = class(TForm)
    ROMessage: TROBinMessage;
    ROChannel: TROWinInetHTTPChannel;
    RORemoteService: TRORemoteService;
    Button1: TButton;
    Button2: TButton;
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  ClientForm: TClientForm;

implementation

{
  The unit TestLibrary_Intf.pas will be generated by the RemObjects preprocessor the first time you
  compile your server application. Make sure to do that before trying to compile the client.

  To invoke your server simply typecast your server to the name of the service interface like this:

      (RORemoteService as ITestService).Sum(1,2)
}

uses TestLibrary_Intf; 

{$R *.dfm}

procedure TClientForm.Button1Click(Sender: TObject);
var
  MyService : ITestService;
  Res       : Integer;
begin
  MyService := CoTestService.Create(ROMessage, ROChannel);
  Res := MyService.Sum(1, 3);
  ShowMessage(IntToStr(Res));
end;

procedure TClientForm.Button2Click(Sender: TObject);
var
  MyService : ITestService;
  Res       : TDateTime;
begin
  MyService := CoTestService.Create(ROMessage, ROChannel);
  Res := MyService.GetServerTime;
  ShowMessage(DateToStr(Res));
end;

end.
