unit TestService_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, 
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Required:} uRORemoteDataModule,
  {Generated:} TestLibrary_Intf;

type
  { TTestService }
  TTestService = class(TRORemoteDataModule, ITestService)
  private
  protected
    { ITestService methods }
    function Sum(const A: Integer; const B: Integer): Integer;
    function GetServerTime: DateTime;
  end;

implementation

{$R *.dfm}
uses
  {Generated:} TestLibrary_Invk;

procedure Create_TestService(out anInstance : IUnknown);
begin
  anInstance := TTestService.Create(nil);
end;

{ TestService }
function TTestService.Sum(const A: Integer; const B: Integer): Integer;
begin
  Result := A + B;
end;

function TTestService.GetServerTime: DateTime;
begin
  Result := Now;
end;

initialization
  TROClassFactory.Create('TestService', Create_TestService, TTestService_Invoker);

finalization

end.
